/**
 * Real Hidalgo County foreclosure notices, manually transcribed (by vision
 * reading, not OCR/AI extraction) from 83 scanned PDFs recorded with the
 * Hidalgo County Clerk in 2026. One of the 83 source documents was a
 * duplicate/reposted notice of another case in this set and is not
 * represented here, leaving 82 distinct cases.
 *
 * The original PDFs are bundled at apps/web/public/hidalgo-source-docs/ and
 * referenced below by filename so the app's "View original" links point at
 * the real recorded document.
 *
 * Every field below is taken directly from the notice text unless the case
 * has a `dataQualityNote`, which explains a specific legibility or
 * consistency issue in the source document. Fields the notice did not state
 * (no street address, no stated principal, etc.) are left null rather than
 * inferred or estimated.
 */

export type AddressMethod = "EXPLICIT_STATED" | "COMMONLY_KNOWN_AS_PHRASE" | "UNRESOLVED";
export type EntityKind = "INDIVIDUAL" | "ENTITY";
export type Classification = "RESIDENTIAL" | "COMMERCIAL" | "UNKNOWN";

export interface RealHidalgoCase {
  docNumber: string;
  pdfFilename: string;
  address: string | null;
  city: string | null;
  zip: string | null;
  addressMethod: AddressMethod;
  legalRawText: string | null;
  subdivision: string | null;
  lot: string | null;
  block: string | null;
  saleDateISO: string;
  saleTime: string;
  saleLocation: string;
  dotDateISO: string | null;
  instrumentNumber: string | null;
  grantorNames: string;
  entityType: EntityKind;
  origMortgagee: string | null;
  currentMortgagee: string;
  servicerName: string | null;
  principalCents: number | null;
  classification: Classification;
  dataQualityNote: string | null;
  manualReview: boolean;
}

const ADMIN_BLDG = "Hidalgo County Administrative Building, 2802 S. Business Hwy 281, Edinburg, TX 78539 (or as designated by the Commissioners Court)";
const COURTHOUSE = "Hidalgo County Courthouse / Clerk's Record Management Facility, 317 N. Closner Blvd, Edinburg, TX 78539";
const AREA_DESIGNATED = "Area designated by the Hidalgo County Commissioners Court";

export const realHidalgoCases: RealHidalgoCase[] = [
  { docNumber: "117910", pdfFilename: "18118310_300452813_docimage_actual.pdf", address: "1706 Quartz Street", city: "Penitas", zip: "78576", addressMethod: "EXPLICIT_STATED", legalRawText: null, subdivision: null, lot: null, block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2008-01-29", instrumentNumber: "2008-1855047", grantorNames: "Guadalupe Benavides; Gilbert Benavides and Erica L. Benavides", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for originating lender", currentMortgagee: "MidFirst Bank", servicerName: "Midland Mortgage, a division of MidFirst Bank", principalCents: 14_275_900, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "117912", pdfFilename: "18118310_300456286_docimage_actual.pdf", address: "817 Jay Dr", city: "Palmhurst", zip: "78573", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 41, James-Allen Subdivision, Hidalgo County, Texas, Vol 20 Pg 172", subdivision: "James-Allen Subdivision", lot: "41", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM - 1:00 PM", saleLocation: ADMIN_BLDG, dotDateISO: "2021-06-14", instrumentNumber: "3234116", grantorNames: "Rosalinda Garcia", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for CrossCountry Mortgage LLC", currentMortgagee: "CrossCountry Mortgage, LLC", servicerName: null, principalCents: 19_146_800, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "117918", pdfFilename: "18118310_301897937_docimage_actual.pdf", address: "1313 13th Street", city: "Mercedes", zip: "78570", addressMethod: "EXPLICIT_STATED", legalRawText: null, subdivision: null, lot: null, block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2002-11-15", instrumentNumber: "1146504", grantorNames: "Mary A. Sanchez; Jorge Alberto Hernandez Jr.", entityType: "INDIVIDUAL", origMortgagee: "MERS", currentMortgagee: "U.S. Bank National Association, as Trustee for Structured Asset Securities Corp Mortgage Loan Trust 2006-RF4", servicerName: "NewRez LLC d/b/a Shellpoint Mortgage Servicing", principalCents: 8_353_400, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "117920", pdfFilename: "18118310_301897941_docimage_actual.pdf", address: "2306 Soleado St", city: "Mission", zip: "78572", addressMethod: "EXPLICIT_STATED", legalRawText: null, subdivision: null, lot: null, block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2020-03-20", instrumentNumber: "3101389", grantorNames: "Ana Vely Uresti, joined by spouse Jose Humberto Munoz-Rios", entityType: "INDIVIDUAL", origMortgagee: "MERS", currentMortgagee: "CrossCountry Mortgage, LLC", servicerName: "Rocket Mortgage, LLC s/b/m Nationstar Mortgage LLC", principalCents: 14_276_600, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "117928", pdfFilename: "18118310_301898510_docimage_actual.pdf", address: "110 Dyanez St", city: "Mercedes", zip: "78570", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 123, Mid-Valley Meadows Phase II, Mercedes, Hidalgo County, Texas, Doc 2971647", subdivision: "Mid-Valley Meadows Phase II", lot: "123", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2023-02-24", instrumentNumber: "3424731", grantorNames: "Cassandra Marie Sanchez and Abel Lee Rodriguez, wife and husband", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for Everett Financial Inc dba Supreme Lending", currentMortgagee: "Rocket Mortgage, LLC s/b/m Nationstar Mortgage LLC", servicerName: null, principalCents: 19_784_900, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "117931", pdfFilename: "18118310_301898513_docimage_actual.pdf", address: null, city: "Alamo", zip: null, addressMethod: "UNRESOLVED", legalRawText: "ALL OF LOT 6 AND WEST 1/2 OF LOT 7, BLOCK 75, Original Townsite of Alamo, Hidalgo County, Texas, Vol 15 Pg 33", subdivision: "Original Townsite of Alamo", lot: "6 and W1/2 of 7", block: "75", saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2018-03-02", instrumentNumber: "2894132", grantorNames: "Jaclyn Galvan, single woman", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for Nations Direct Mortgage LLC dba Motive Lending", currentMortgagee: "PennyMac Loan Services, LLC", servicerName: null, principalCents: 8_787_800, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "117929", pdfFilename: "18118310_301898514_docimage_actual.pdf", address: "1700 Magdalena Ave", city: "Mission", zip: "78572", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 150, Vacating and Resubdivision of Ala Blanca-Norte Subdivision Unit No 2, Mission, Hidalgo County, Texas, Vol 20 Pg 190", subdivision: "Vacating and Resubdivision of Ala Blanca-Norte Subdivision Unit No 2", lot: "150", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2018-11-20", instrumentNumber: "2968140", grantorNames: "Rigoberto L. Salinas and Maria Haydee Ramirez, husband and wife", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for Willow Bend Mortgage Company LLC", currentMortgagee: "Rocket Mortgage LLC s/b/m Nationstar Mortgage LLC", servicerName: null, principalCents: 6_382_200, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "117925", pdfFilename: "18118310_301898517_docimage_actual.pdf", address: null, city: "San Juan", zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOTS 66, Ebano Heights Phase 1, San Juan, Hidalgo County, Texas, Vol 26 Pg 160A", subdivision: "Ebano Heights Phase 1", lot: "66", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: AREA_DESIGNATED, dotDateISO: "2016-12-22", instrumentNumber: "2773604", grantorNames: "Rogelio Garza Jr. and Sarah Garza, husband and wife", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for Willow Bend Mortgage Company LLC", currentMortgagee: "PennyMac Loan Services, LLC", servicerName: null, principalCents: null, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "117940", pdfFilename: "18118310_301898975_docimage_actual.pdf", address: null, city: null, zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 84, Vista Ridge Acres Phase V, Hidalgo County, Texas, Doc 2014-2573878", subdivision: "Vista Ridge Acres Phase V", lot: "84", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2021-01-11", instrumentNumber: "3183736", grantorNames: "Mario Cesar Gonzalez Jr, single man", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for Hometown Lenders Inc", currentMortgagee: "PennyMac Loan Services, LLC", servicerName: null, principalCents: null, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "117949", pdfFilename: "18118310_302089613_docimage_actual.pdf", address: "1337 E Candor Dr", city: "Edinburg", zip: "78542", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 50, Sonador Coves Subdivision Phase 1, Edinburg, Hidalgo County, Texas, Doc 3163772", subdivision: "Sonador Coves Subdivision Phase 1", lot: "50", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2021-12-17", instrumentNumber: "3293972", grantorNames: "Jennifer Daisy Torres", entityType: "INDIVIDUAL", origMortgagee: null, currentMortgagee: "Carrington Mortgage Services, LLC", servicerName: null, principalCents: 24_209_200, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "117950", pdfFilename: "18118310_302089614_docimage_actual.pdf", address: "1804 Lago Michigan", city: "Edinburg", zip: "78542", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 110, Lumen Subdivision Phase B, Edinburg, Hidalgo County, Texas, Doc 2844940", subdivision: "Lumen Subdivision Phase B", lot: "110", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2022-04-26", instrumentNumber: "3336298", grantorNames: "Cristella Ozuna", entityType: "INDIVIDUAL", origMortgagee: null, currentMortgagee: "CrossCountry Mortgage LLC", servicerName: "Rocket Mortgage LLC s/b/m Nationstar Mortgage LLC", principalCents: 30_929_400, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "117951", pdfFilename: "18118310_302089620_docimage_actual.pdf", address: null, city: "McAllen", zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 50, Green Meadows Subdivision, McAllen, Hidalgo County, Texas, Vol 22 Pg 72", subdivision: "Green Meadows Subdivision", lot: "50", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: AREA_DESIGNATED, dotDateISO: "2021-11-02", instrumentNumber: "3280387", grantorNames: "Jeanette De La Rosa, unmarried woman", entityType: "INDIVIDUAL", origMortgagee: null, currentMortgagee: "Lakeview Loan Servicing LLC", servicerName: "LoanCare LLC", principalCents: null, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "117957", pdfFilename: "18118310_302091881_docimage_actual.pdf", address: "2318 Flushing Meadows", city: "Weslaco", zip: "78596", addressMethod: "COMMONLY_KNOWN_AS_PHRASE", legalRawText: "LOT 3, BLOCK 3, Hidden Valley Subdivision Phase 1, Weslaco, Hidalgo County, Texas, Vol 33 Pg 141", subdivision: "Hidden Valley Subdivision Phase 1", lot: "3", block: "3", saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: COURTHOUSE, dotDateISO: "2024-05-28", instrumentNumber: "3552099", grantorNames: "John James Salopek IV and Colleen Salopek, husband and wife", entityType: "INDIVIDUAL", origMortgagee: null, currentMortgagee: "Freedom Mortgage Corporation", servicerName: null, principalCents: null, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "117958", pdfFilename: "18118310_302091887_docimage_actual.pdf", address: "801 West Hawk Avenue", city: "Pharr", zip: "78577", addressMethod: "EXPLICIT_STATED", legalRawText: "LOTS 10, 11, 12, BLOCK 117, Evans Resubdivision of Lot 175 of Kelly Pharr, City of Pharr, Hidalgo County, Texas, Vol 7 Pg 55", subdivision: "Evans Resubdivision of Lot 175 of Kelly Pharr", lot: "10, 11, 12", block: "117", saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2016-09-26", instrumentNumber: "2753056", grantorNames: "Annabel Lopez and Arnulfo Lopez Jr., wife and husband", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for Ditech Financial LLC", currentMortgagee: "NewRez LLC", servicerName: "Shellpoint Mortgage Servicing", principalCents: 6_780_000, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "117991", pdfFilename: "18118310_302242285_docimage_actual.pdf", address: "603 Miguel Hidalgo St", city: "San Juan", zip: "78589", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 12, BLOCK 2, Tierra Del Sol Subdivision Unit 2, San Juan, Hidalgo County, Texas, Vol 19 Pg 105", subdivision: "Tierra Del Sol Subdivision Unit 2", lot: "12", block: "2", saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2019-10-03", instrumentNumber: "3053795", grantorNames: "Prescilla Garza and Raul Hernandez", entityType: "INDIVIDUAL", origMortgagee: null, currentMortgagee: "Lakeview Loan Servicing LLC", servicerName: "M&T Bank", principalCents: 17_183_000, classification: "RESIDENTIAL", dataQualityNote: "Deed of Trust has a correction instrument (3758296) referenced alongside the original.", manualReview: false },
  { docNumber: "117992", pdfFilename: "18118310_302242287_docimage_actual.pdf", address: "915 Mazatlan St", city: "Mission", zip: "78572", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 255, Tierra Linda Subdivision, Palmview, Hidalgo County, Texas, Vol 24 Pg 11-12", subdivision: "Tierra Linda Subdivision", lot: "255", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2020-09-10", instrumentNumber: "3147158", grantorNames: "David Olivarez", entityType: "INDIVIDUAL", origMortgagee: null, currentMortgagee: "Onslow Bay Financial LLC", servicerName: "Rocket Mortgage, LLC", principalCents: 10_450_000, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "117993", pdfFilename: "18118310_302242288_docimage_actual.pdf", address: null, city: "Alamo", zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 7, Alma-Delia Subdivision, City of Alamo, Hidalgo County, Texas, Vol 44 Pg 139", subdivision: "Alma-Delia Subdivision", lot: "7", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: AREA_DESIGNATED, dotDateISO: "2023-07-21", instrumentNumber: "3469585", grantorNames: "The Pike Investment Company LLC, a Texas LLC; also signed by Cristela Rodriguez Riojas", entityType: "ENTITY", origMortgagee: "Commercial Loan Funding, LLC", currentMortgagee: "Wilmington Savings Fund Society, FSB as Trustee for IBIS Holdings A Trust", servicerName: "Fay Servicing, LLC", principalCents: null, classification: "COMMERCIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "117999", pdfFilename: "18118310_302247011_docimage_actual.pdf", address: "509 Central Park Street", city: "Edinburg", zip: "78541", addressMethod: "COMMONLY_KNOWN_AS_PHRASE", legalRawText: "LOT 56, Russell Park Subdivision Phase II, Edinburg, Hidalgo County, Texas, Doc 3028460", subdivision: "Russell Park Subdivision Phase II", lot: "56", block: null, saleDateISO: "2026-10-06", saleTime: "10:00 AM", saleLocation: COURTHOUSE, dotDateISO: "2023-11-21", instrumentNumber: "3501695", grantorNames: "Jose De Jesus Osegueda and Blanca Flor Osegueda, husband and wife", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for Plaza Home Mortgage Inc", currentMortgagee: "Freedom Mortgage Corporation", servicerName: null, principalCents: null, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118006", pdfFilename: "18118310_302298093_docimage_actual.pdf", address: "110 E Gore Ave", city: "Pharr", zip: "78577", addressMethod: "EXPLICIT_STATED", legalRawText: null, subdivision: null, lot: null, block: null, saleDateISO: "2026-10-06", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2020-10-23", instrumentNumber: "3160378", grantorNames: "Victoria Jo Casas, unmarried woman", entityType: "INDIVIDUAL", origMortgagee: null, currentMortgagee: "Lakeview Loan Servicing LLC", servicerName: "LoanCare LLC", principalCents: 18_655_800, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118158", pdfFilename: "18118310_302334146_docimage_actual.pdf", address: null, city: "Edinburg", zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 70, Monte Cristo Park Subdivision Phase I, Edinburg, Hidalgo County, Texas, Vol 36 Pg 188", subdivision: "Monte Cristo Park Subdivision Phase I", lot: "70", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2019-07-18", instrumentNumber: "3042125", grantorNames: "Jose Antonio Castro and Cassandra Stephannie Huerta Garcia, married", entityType: "INDIVIDUAL", origMortgagee: null, currentMortgagee: "Bank of New York Mellon, as Indenture Trustee for WIMC Capital Trust 2011-1", servicerName: "Shellpoint Mortgage Servicing", principalCents: 7_250_000, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118183", pdfFilename: "18118310_302546458_docimage_actual.pdf", address: "601 Quarry Dr", city: "Mission", zip: "78573", addressMethod: "COMMONLY_KNOWN_AS_PHRASE", legalRawText: "LOT 15, Mayberry Meadows Subdivision, Alton, Hidalgo County, Texas, Doc 3391665", subdivision: "Mayberry Meadows Subdivision", lot: "15", block: null, saleDateISO: "2026-10-06", saleTime: "10:00 AM", saleLocation: COURTHOUSE, dotDateISO: "2024-10-15", instrumentNumber: "3590626", grantorNames: "Juan A Gil and Ashley Gil, husband and wife", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for Guaranteed Rate Inc", currentMortgagee: "Freedom Mortgage Corporation", servicerName: null, principalCents: null, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118186", pdfFilename: "18118310_302546459_docimage_actual.pdf", address: "2504 S Dogwood St", city: "Pharr", zip: "78577", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 28, Las Arboledas Subdivision, Hidalgo County, Texas, Vol 48 Pg 78", subdivision: "Las Arboledas Subdivision", lot: "28", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: AREA_DESIGNATED, dotDateISO: "2006-11-13", instrumentNumber: "2006-1689521", grantorNames: "Judith Vivian, joined by spouse Victor Ramon Quintanilla", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for WMC Mortgage Corp", currentMortgagee: "Deutsche Bank National Trust Company, as Trustee for Soundview Home Loan Trust 2007-WMC1", servicerName: null, principalCents: null, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118187", pdfFilename: "18118310_302546460_docimage_actual.pdf", address: "7507 Camelot Drive", city: "Mission", zip: "78572", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 90, Squire Estates Subdivision, Mission, Hidalgo County, Texas, Vol 28 Pg 62", subdivision: "Squire Estates Subdivision", lot: "90", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM - 4:00 PM", saleLocation: COURTHOUSE, dotDateISO: "2017-10-17", instrumentNumber: "2859044", grantorNames: "Carlos Salinas, unmarried", entityType: "INDIVIDUAL", origMortgagee: "Compass Bank", currentMortgagee: "PNC Bank, National Association", servicerName: null, principalCents: null, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118184", pdfFilename: "18118310_302546462_docimage_actual.pdf", address: "5114 June Court", city: "Edinburg", zip: "78539", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 57, Summerset Estates Subdivision, Edinburg, Hidalgo County, Texas, Doc 2542224", subdivision: "Summerset Estates Subdivision", lot: "57", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM - 4:00 PM", saleLocation: COURTHOUSE, dotDateISO: "2023-11-16", instrumentNumber: "3503848", grantorNames: "Laura B. Tiscareno, unmarried woman", entityType: "INDIVIDUAL", origMortgagee: "PNC Bank, National Association", currentMortgagee: "PNC Bank, National Association", servicerName: null, principalCents: null, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118188", pdfFilename: "18118310_302546468_docimage_actual.pdf", address: "904 Rio Grande Dr", city: "Mission", zip: "78572", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 25, BLOCK 26, Cimarron Country Club Phase I Section III, Mission, Hidalgo County, Texas, Vol 23 Pg 200", subdivision: "Cimarron Country Club Phase I Section III", lot: "25", block: "26", saleDateISO: "2026-09-01", saleTime: "10:00 AM - 1:00 PM", saleLocation: ADMIN_BLDG, dotDateISO: "2021-05-18", instrumentNumber: "3226306", grantorNames: "Homes4Money LLC and Robert Capetillo", entityType: "ENTITY", origMortgagee: "Civic Financial Services, LLC", currentMortgagee: "U.S. Bank Trust National Association, as owner trustee for Legacy Mortgage Asset Trust 2024-INV1", servicerName: "Fay Servicing LLC", principalCents: null, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118185", pdfFilename: "18118310_302546476_docimage_actual.pdf", address: "2805 Huisache", city: "Hidalgo", zip: "78557", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 135, Valle Alto North Unit III, Hidalgo, Hidalgo County, Texas, Vol 32 Pg 113", subdivision: "Valle Alto North Unit III", lot: "135", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: AREA_DESIGNATED, dotDateISO: "1998-12-03", instrumentNumber: "732755", grantorNames: "Carlo G Colunga and Paula E Colunga", entityType: "INDIVIDUAL", origMortgagee: "United States of America, acting through Rural Housing Service / USDA", currentMortgagee: "United States of America, acting through Rural Housing Service, USDA", servicerName: null, principalCents: null, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118191", pdfFilename: "18118310_302546477_docimage_actual.pdf", address: "311 S Paseo Del Rey St", city: "Mission", zip: "78572", addressMethod: "EXPLICIT_STATED", legalRawText: null, subdivision: null, lot: null, block: null, saleDateISO: "2026-10-06", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2019-02-28", instrumentNumber: "2993531", grantorNames: "Ramon Rodriguez Guzman and Dina Y Barrios Felix, husband and wife", entityType: "INDIVIDUAL", origMortgagee: "MERS", currentMortgagee: "Lakeview Loan Servicing, LLC", servicerName: "Rocket Mortgage LLC s/b/m Nationstar Mortgage LLC", principalCents: 17_072_900, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118192", pdfFilename: "18118310_302546483_docimage_actual.pdf", address: "7729 Villa Rama South", city: "Mission", zip: "78572", addressMethod: "EXPLICIT_STATED", legalRawText: null, subdivision: null, lot: null, block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2005-08-22", instrumentNumber: "2005-1514346", grantorNames: "Julio C Davila and Sonia P Davila, husband and wife", entityType: "INDIVIDUAL", origMortgagee: "MERS", currentMortgagee: "Wells Fargo Bank, N.A.", servicerName: null, principalCents: 14_301_000, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118189", pdfFilename: "18118310_302546485_docimage_actual.pdf", address: "4104 Ulex Avenue", city: "McAllen", zip: "78504", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 15, La Cantera Estates Subdivision, McAllen, Hidalgo County, Texas, Vol 47 Pg 177", subdivision: "La Cantera Estates Subdivision", lot: "15", block: null, saleDateISO: "2026-10-06", saleTime: "10:00 AM - 1:00 PM", saleLocation: COURTHOUSE, dotDateISO: "2021-03-05", instrumentNumber: "3199707", grantorNames: "Juan Manuel Garcia and Bertha Cynthia De La Fuente", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for Amcap Mortgage Ltd dba Gold Financial Services", currentMortgagee: "Planet Home Lending, LLC", servicerName: null, principalCents: null, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "117716", pdfFilename: "18118310_300258600_docimage_actual.pdf", address: null, city: "Edinburg", zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 5, BLOCK 1, Gateway City Subdivision, Edinburg, Hidalgo County, Texas, Vol 14 Pg 43", subdivision: "Gateway City Subdivision", lot: "5", block: "1", saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2022-01-04", instrumentNumber: "3297966", grantorNames: "Juan Manuel Montes Jr and Alma Juliette Montes, husband and wife", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for Synergy One Lending Inc", currentMortgagee: "Rocket Mortgage, LLC s/b/m Nationstar Mortgage LLC", servicerName: null, principalCents: 14_924_600, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "117732", pdfFilename: "18118310_300344075_docimage_actual.pdf", address: null, city: "McAllen", zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 10, BLOCK 5, Whitewing Addition Unit 1, McAllen, Hidalgo County, Texas, Vol 17 Pg 2", subdivision: "Whitewing Addition Unit 1", lot: "10", block: "5", saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2019-08-05", instrumentNumber: "3037223", grantorNames: "Nelson Jair Cruz and Claudia Cecilia Alvarez Cruz, husband and wife", entityType: "INDIVIDUAL", origMortgagee: "NewRez LLC (successor to original lender)", currentMortgagee: "NewRez LLC", servicerName: null, principalCents: 12_617_200, classification: "RESIDENTIAL", dataQualityNote: "Source document states two different Deed of Trust dates in different sections (Note date August 5, 2019 vs. a June 28, 2018 reference elsewhere); recorded as stated.", manualReview: true },
  { docNumber: "117911", pdfFilename: "18118310_300452817_docimage_actual.pdf", address: "410 Chula Vista Drive", city: "San Juan", zip: "78589", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 126, Chula Vista Estates Phase I, San Juan, Hidalgo County, Texas, Vol 24 Pg 47-B", subdivision: "Chula Vista Estates Phase I", lot: "126", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2008-03-17", instrumentNumber: "2008-1871818", grantorNames: "Gabriela Hinojosa, unmarried woman", entityType: "INDIVIDUAL", origMortgagee: "MERS", currentMortgagee: "MidFirst Bank", servicerName: "Midland Mortgage, a division of MidFirst Bank", principalCents: 7_028_800, classification: "RESIDENTIAL", dataQualityNote: "A second notice for the same Deed of Trust and property was posted later in the source set (duplicate/reposted sale notice, not seeded separately).", manualReview: false },
  { docNumber: "117927", pdfFilename: "18118310_301898516_docimage_actual.pdf", address: null, city: "Edinburg", zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 83, Rogers Coves Subdivision Phase A, Edinburg, Hidalgo County, Texas, Doc 3455990", subdivision: "Rogers Coves Subdivision Phase A", lot: "83", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2024-12-05", instrumentNumber: "3604303", grantorNames: "Nelda Saldivar, unmarried woman, and Aida Saldivar Lujan, unmarried woman", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for Nations Lending Corporation", currentMortgagee: "Nations Lending Corporation", servicerName: "LoanCare, LLC", principalCents: 26_938_700, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "117936", pdfFilename: "18118310_301898984_docimage_actual.pdf", address: null, city: "Mercedes", zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 17, BLOCK 63, Original Townsite of Mercedes, Hidalgo County, Texas, Vol U Pg 20-21", subdivision: "Original Townsite of Mercedes", lot: "17", block: "63", saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2014-05-22", instrumentNumber: "2014-2515834", grantorNames: "Maxine Torres, unmarried woman", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for Ark-La-Tex Financial Services LLC dba Benchmark Mortgage", currentMortgagee: "Wells Fargo Bank, N.A.", servicerName: null, principalCents: null, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "117990", pdfFilename: "18118310_302242281_docimage_actual.pdf", address: null, city: "Weslaco", zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 115, Las Brisas Del Oro Unit 2, Weslaco, Hidalgo County, Texas, Vol 32 Pg 165", subdivision: "Las Brisas Del Oro Unit 2", lot: "115", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2024-02-27", instrumentNumber: "3526625", grantorNames: "Esteban Efrain Rivas Jr, a single man", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for Lower, LLC", currentMortgagee: "Planet Home Lending LLC", servicerName: null, principalCents: null, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "117994", pdfFilename: "18118310_302242286_docimage_actual.pdf", address: "212 Caramel Dr", city: "Alamo", zip: "78516", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 34, Valle Dulce Subdivision Phase 1, Alamo, Hidalgo County, Texas, Vol 39 Pg 12", subdivision: "Valle Dulce Subdivision Phase 1", lot: "34", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2020-12-29", instrumentNumber: "3181523", grantorNames: "Eva Adriana Vergel and Jose Alfredo Perales", entityType: "INDIVIDUAL", origMortgagee: null, currentMortgagee: "Freedom Mortgage Corporation", servicerName: null, principalCents: 13_795_400, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118133", pdfFilename: "18118310_302324146_docimage_actual.pdf", address: "4308 Fresno Dr", city: "Donna", zip: "78537", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 18, La Blanca Heights, Hidalgo County, Texas, Vol 21 Pg 59", subdivision: "La Blanca Heights", lot: "18", block: null, saleDateISO: "2026-10-06", saleTime: "10:00 AM - 4:00 PM", saleLocation: ADMIN_BLDG, dotDateISO: "2022-05-17", instrumentNumber: "3344170", grantorNames: "Rene Garcia Rodriguez, unmarried man", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for Gateway Mortgage, a division of Gateway First Bank", currentMortgagee: "Lakeview Loan Servicing, LLC", servicerName: null, principalCents: null, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118157", pdfFilename: "18118310_302334131_docimage_actual.pdf", address: null, city: null, zip: null, addressMethod: "UNRESOLVED", legalRawText: "The North 315 feet of the East 468.48 feet of LOT 16, BLOCK 43, Capisallo District Subdivision, Hidalgo County, Texas, Vol P Pg 226", subdivision: "Capisallo District Subdivision", lot: "16 (N 315ft of E 468.48ft)", block: "43", saleDateISO: "2026-10-06", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2020-02-14", instrumentNumber: "3090431", grantorNames: "Samuel Porras Mancinas and Patricia Garcia, husband and wife", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for Academy Mortgage Corporation", currentMortgagee: "NewRez LLC", servicerName: "Shellpoint Mortgage Servicing", principalCents: 31_764_000, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118156", pdfFilename: "18118310_302334132_docimage_actual.pdf", address: null, city: null, zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 22, Cotton Estates Central Subdivision, Hidalgo County, Texas, Vol 47 Pg 126-127", subdivision: "Cotton Estates Central Subdivision", lot: "22", block: null, saleDateISO: "2026-10-06", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2012-08-15", instrumentNumber: "2012-2335975", grantorNames: "Michael A. Gonzales and wife Illiana S. Perez", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for NTFN Inc", currentMortgagee: "Rocket Mortgage, LLC", servicerName: "Mr. Cooper", principalCents: 23_381_800, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118190", pdfFilename: "18118310_302546466_docimage_actual.pdf", address: "1807 15 1/2 Street", city: "Mission", zip: "78572", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 241, Southern Oak Subdivision Phase 3, Hidalgo County, Texas, Vol 38 Pg 10", subdivision: "Southern Oak Subdivision Phase 3", lot: "241", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2003-08-01", instrumentNumber: "1271865", grantorNames: "Melissa Garza and Jorge Luis Trevino", entityType: "INDIVIDUAL", origMortgagee: "Grande Valley Homes, LLC", currentMortgagee: "U.S. Bank National Association, as Trustee of NRZ Pass-Through Trust VII-B (Pref)", servicerName: "Shellpoint Mortgage Servicing", principalCents: 6_942_700, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118199", pdfFilename: "18118310_303539013_docimage_actual.pdf", address: null, city: "Hidalgo", zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 110, Rio Largo Estates II, Hidalgo, Hidalgo County, Texas, Vol 35 Pg 74", subdivision: "Rio Largo Estates II", lot: "110", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: AREA_DESIGNATED, dotDateISO: "2001-03-01", instrumentNumber: "952710", grantorNames: "Jose J. Cuellar and wife Rebeca Hinojosa", entityType: "INDIVIDUAL", origMortgagee: "United States of America, acting through Rural Housing Service / USDA", currentMortgagee: "United States of America, acting through Rural Housing Service, USDA", servicerName: "Dawson's Management - USDA", principalCents: null, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118200", pdfFilename: "18118310_303539014_docimage_actual.pdf", address: null, city: "Pharr", zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 27, Arnold Grove Subdivision, Pharr, Hidalgo County, Texas, Doc 3406744", subdivision: "Arnold Grove Subdivision", lot: "27", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2023-02-22", instrumentNumber: "3426265", grantorNames: "Jose Alberto Garza, married person", entityType: "INDIVIDUAL", origMortgagee: "Security Service Federal Credit Union", currentMortgagee: "Security Service Federal Credit Union", servicerName: "Cenlar FSB", principalCents: 5_560_000, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118203", pdfFilename: "18118310_303547556_docimage_actual.pdf", address: null, city: "Mission", zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 29, Sharyland Plantation Village Las Placitas Subdivision Phase I, Mission, Hidalgo County, Texas, Vol 46 Pg 149", subdivision: "Sharyland Plantation Village Las Placitas Subdivision Phase I", lot: "29", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2007-01-31", instrumentNumber: "2007-1719558", grantorNames: "Barbara Jean Dennis, a single woman", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for Meridias Capital Inc", currentMortgagee: "JPMorgan Chase Bank NA, as successor by merger to J.P. Morgan Mortgage Acquisition Corp", servicerName: "Rocket Mortgage LLC", principalCents: null, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118209", pdfFilename: "18118310_306756759_docimage_actual.pdf", address: "605 W Polk Ave", city: "Alton", zip: "78573", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 35, Comarex Subdivision, Alton, Hidalgo County, Texas, Doc 3012114", subdivision: "Comarex Subdivision", lot: "35", block: null, saleDateISO: "2026-10-06", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2020-06-19", instrumentNumber: "3123033", grantorNames: "Ruth M Flores and Marcos Olivares-Rodriguez", entityType: "INDIVIDUAL", origMortgagee: null, currentMortgagee: "PennyMac Loan Services, LLC", servicerName: null, principalCents: 15_612_000, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118210", pdfFilename: "18118310_306756765_docimage_actual.pdf", address: null, city: null, zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 3, BLOCK 10, South San Carlos Subdivision, Hidalgo County, Texas", subdivision: "South San Carlos Subdivision", lot: "3", block: "10", saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: AREA_DESIGNATED, dotDateISO: "2006-02-23", instrumentNumber: "2006-1590410", grantorNames: "Armando Casas and Ludivina Casas aka Ludi Casas, married couple", entityType: "INDIVIDUAL", origMortgagee: "Beneficial Texas Inc", currentMortgagee: "U.S. Bank Trust National Association, as Trustee of LSF9 Master Participation Trust", servicerName: "Fay Servicing LLC", principalCents: 2_798_970, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118214", pdfFilename: "18118310_306766119_docimage_actual.pdf", address: "2404 North 19 1/2 St", city: "McAllen", zip: "78501", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 15, Del-Lou Subdivision, McAllen, Hidalgo County, Texas, Vol 19 Pg 109", subdivision: "Del-Lou Subdivision", lot: "15", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM - 1:00 PM", saleLocation: ADMIN_BLDG, dotDateISO: "2010-07-21", instrumentNumber: "2010-2124025", grantorNames: "Jose R. Flores and Elida R. Flores", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for Amerigroup Mortgage Corporation, a division of Mortgage Investors Corporation", currentMortgagee: "U.S. Bank National Association, as Trustee for RMTP Trust Series 2021 BKM-TT-V", servicerName: "Nationstar Mortgage LLC", principalCents: null, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118216", pdfFilename: "18118310_306771234_docimage_actual.pdf", address: "1003 Inspiration Drive", city: "Pharr", zip: "78577", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 26, Encanto Ridge, Pharr, Hidalgo County, Texas, Vol 31 Pg 133", subdivision: "Encanto Ridge", lot: "26", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "1999-12-09", instrumentNumber: "831515", grantorNames: "Rene Ramirez and wife Laura Ramirez", entityType: "INDIVIDUAL", origMortgagee: "Mortgages Unlimited, Inc.", currentMortgagee: "Apex Bank", servicerName: null, principalCents: 50_000_000, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118215", pdfFilename: "18118310_306771239_docimage_actual.pdf", address: "3521 S Peak Rd", city: "Edinburg", zip: "78542", addressMethod: "COMMONLY_KNOWN_AS_PHRASE", legalRawText: "LOT 9, The Heights on Wisconsin III, Edinburg, Hidalgo County, Texas, Doc 3473084", subdivision: "The Heights on Wisconsin III", lot: "9", block: null, saleDateISO: "2026-10-06", saleTime: "10:00 AM", saleLocation: COURTHOUSE, dotDateISO: "2024-02-12", instrumentNumber: "3522035", grantorNames: "Juan Miguel Anzaldua Moncada a/k/a Juan Miguel Anzaldua and Lorianna Lynn Lerma, husband and wife", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for Interlinc Mortgage Services, LLC", currentMortgagee: "Freedom Mortgage Corporation", servicerName: null, principalCents: null, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118217", pdfFilename: "18118310_307467746_docimage_actual.pdf", address: "2500 Violet Ave", city: "McAllen", zip: "78504", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 181, Kingwood Subdivision Phase VII, Hidalgo County, Texas, Vol 44 Pg 58", subdivision: "Kingwood Subdivision Phase VII", lot: "181", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2013-06-21", instrumentNumber: "2013-2425508", grantorNames: "Joel A Rodriguez", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for Freedom Mortgage Corporation", currentMortgagee: "Lakeview Loan Servicing, LLC", servicerName: "LoanCare LLC", principalCents: 14_752_100, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118218", pdfFilename: "18118310_307467748_docimage_actual.pdf", address: "1904 W 26th St", city: "Mission", zip: "78572", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 43, Montecristo Subdivision, Mission, Hidalgo County, Texas, Clerk's File 2920007", subdivision: "Montecristo Subdivision", lot: "43", block: null, saleDateISO: "2026-11-03", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2021-10-18", instrumentNumber: "3273887", grantorNames: "Christopher Lee Tarbutton, unmarried man", entityType: "INDIVIDUAL", origMortgagee: "MERS beneficiary (lender Willow Bend Mortgage Company LLC)", currentMortgagee: "Onity Mortgage Corporation f/k/a PHH Mortgage Corporation", servicerName: null, principalCents: 21_699_700, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118221", pdfFilename: "18118310_308205373_docimage_actual.pdf", address: null, city: null, zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 6, Elite Village Subdivision Phase II, Hidalgo County, Texas, Clerk's File 2239313", subdivision: "Elite Village Subdivision Phase II", lot: "6", block: null, saleDateISO: "2026-09-01", saleTime: "1:00 PM - 4:00 PM", saleLocation: "Hidalgo County, Texas", dotDateISO: "2016-10-19", instrumentNumber: "2759231", grantorNames: "Roberto De La Cerda-Torres and Lynda Marie Mora-Rodriguez", entityType: "INDIVIDUAL", origMortgagee: null, currentMortgagee: "Top Fruit, Inc., a Texas corporation", servicerName: null, principalCents: 3_510_000, classification: "UNKNOWN", dataQualityNote: null, manualReview: false },
  { docNumber: "118222", pdfFilename: "18118310_308205375_docimage_actual.pdf", address: null, city: null, zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 11, Citrus Village Subdivision, Hidalgo County, Texas, Doc 2689617", subdivision: "Citrus Village Subdivision", lot: "11", block: null, saleDateISO: "2026-09-01", saleTime: "1:00 PM - 4:00 PM", saleLocation: "Hidalgo County, Texas", dotDateISO: "2019-07-16", instrumentNumber: "3031625", grantorNames: "Liboria Guerrero Carranza", entityType: "INDIVIDUAL", origMortgagee: null, currentMortgagee: "Top Fruit, Inc., a Texas corporation", servicerName: null, principalCents: 3_470_000, classification: "UNKNOWN", dataQualityNote: null, manualReview: false },
  { docNumber: "118220", pdfFilename: "18118310_308205377_docimage_actual.pdf", address: null, city: null, zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 1, Elite Village Subdivision Phase II, Hidalgo County, Texas, Clerk's File 2239313", subdivision: "Elite Village Subdivision Phase II", lot: "1", block: null, saleDateISO: "2026-09-01", saleTime: "1:00 PM - 4:00 PM", saleLocation: "Hidalgo County, Texas", dotDateISO: "2012-05-17", instrumentNumber: "2310814", grantorNames: "Rosa H. Hernandez and Liliana Perez", entityType: "INDIVIDUAL", origMortgagee: null, currentMortgagee: "Top Fruit, Inc., a Texas corporation", servicerName: null, principalCents: 3_470_000, classification: "UNKNOWN", dataQualityNote: "Sale time not fully legible on source notice; inferred from sibling Top Fruit, Inc. notices posted the same day, which state 1:00 PM - 4:00 PM.", manualReview: true },
  { docNumber: "118225", pdfFilename: "18118310_308946701_docimage_actual.pdf", address: null, city: null, zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 63, San Jacinto Estates No. 7 Subdivision, Hidalgo County, Texas, Clerk's File 2223371", subdivision: "San Jacinto Estates No. 7", lot: "63", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM CST", saleLocation: ADMIN_BLDG, dotDateISO: "2014-04-22", instrumentNumber: "2567015", grantorNames: "Mario Alberto Cabriales and Flor Esthela Alvarez", entityType: "INDIVIDUAL", origMortgagee: null, currentMortgagee: "San Jacinto Enterprises, LLC, a Texas LLC", servicerName: null, principalCents: 3_800_000, classification: "UNKNOWN", dataQualityNote: null, manualReview: false },
  { docNumber: "118228", pdfFilename: "18118310_308946704_docimage_actual.pdf", address: null, city: null, zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 1, San Jacinto Estates No. 9, Hidalgo County, Texas, Clerk's File 2743676", subdivision: "San Jacinto Estates No. 9", lot: "1", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM CST", saleLocation: ADMIN_BLDG, dotDateISO: "2020-02-01", instrumentNumber: "3111608", grantorNames: "Yisban V. Villasana Escandon and Jaret Mariana Hernandez Vasquez", entityType: "INDIVIDUAL", origMortgagee: null, currentMortgagee: "San Jacinto Enterprises, LLC, a Texas LLC", servicerName: null, principalCents: 4_840_000, classification: "UNKNOWN", dataQualityNote: "Property was later conveyed via Assumption Warranty Deed to Eduardo Guzman (May 31, 2022, Doc 3351216); original borrower names are retained as stated in the notice.", manualReview: true },
  { docNumber: "118229", pdfFilename: "18118310_308946709_docimage_actual.pdf", address: null, city: null, zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 22, San Jacinto Estates No 10 Phase I Subdivision, Hidalgo County, Texas, Clerk's File 3276440", subdivision: "San Jacinto Estates No. 10 Phase I", lot: "22", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM CST", saleLocation: ADMIN_BLDG, dotDateISO: "2021-12-09", instrumentNumber: "3290024", grantorNames: "Evelin Hernandez Pinales", entityType: "INDIVIDUAL", origMortgagee: null, currentMortgagee: "San Jacinto Enterprises, LLC, a Texas LLC", servicerName: null, principalCents: 3_850_000, classification: "UNKNOWN", dataQualityNote: null, manualReview: false },
  { docNumber: "118235", pdfFilename: "18118310_309236870_docimage_actual.pdf", address: "1822 W Washington St", city: "Weslaco", zip: "78599", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 58, West Gate Crossing Phase 2, Weslaco, Hidalgo County, Texas, Vol 40 Pg 172", subdivision: "West Gate Crossing Phase 2", lot: "58", block: null, saleDateISO: "2026-10-06", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2015-07-06", instrumentNumber: "2015-2627072", grantorNames: "Daniel Lozano and Tiffany Rose Lozano aka Tiffany R Lozano aka Tiffany Lozano, husband and wife", entityType: "INDIVIDUAL", origMortgagee: "MERS", currentMortgagee: "MidFirst Bank", servicerName: "Midland Mortgage, a division of MidFirst Bank", principalCents: 10_175_000, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118233", pdfFilename: "18118310_309236874_docimage_actual.pdf", address: "921 Jay Drive South", city: "Mission", zip: "78573", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 50, James Allen Subdivision, Hidalgo County, Texas, Vol 20 Pg 172", subdivision: "James Allen Subdivision", lot: "50", block: null, saleDateISO: "2026-10-06", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2009-02-04", instrumentNumber: "2009-1979920", grantorNames: "Abel Juarez Jr and Belinda Juarez, husband and wife", entityType: "INDIVIDUAL", origMortgagee: "MERS", currentMortgagee: "MidFirst Bank", servicerName: "Midland Mortgage, a division of MidFirst Bank", principalCents: 14_143_100, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118231", pdfFilename: "18118310_309236875_docimage_actual.pdf", address: "112 Wisteria Ave", city: "McAllen", zip: "78504", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 11, Queen's Villa Unit No. 1, McAllen, Hidalgo County, Texas, Vol 21 Pg 19", subdivision: "Queen's Villa Unit No. 1", lot: "11", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2021-04-15", instrumentNumber: "3213841", grantorNames: "Sonia Prado, unmarried woman", entityType: "INDIVIDUAL", origMortgagee: "MERS", currentMortgagee: "PennyMac Loan Services, LLC", servicerName: null, principalCents: 19_500_000, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118234", pdfFilename: "18118310_309236878_docimage_actual.pdf", address: "3401 N Whisky Dr", city: "Pharr", zip: "78577", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 26, Buchanan Estates, Pharr, Hidalgo County, Texas, Vol 33 Pg 86A", subdivision: "Buchanan Estates", lot: "26", block: null, saleDateISO: "2026-10-06", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2020-11-18", instrumentNumber: "3169115", grantorNames: "Ricardo Rene Avalos and Belinda Avalos, husband and wife", entityType: "INDIVIDUAL", origMortgagee: "MERS", currentMortgagee: "MidFirst Bank", servicerName: "Midland Mortgage, a division of MidFirst Bank", principalCents: 14_286_400, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118236", pdfFilename: "18118310_309236879_docimage_actual.pdf", address: "4109 Santa Olivia", city: "Mission", zip: "78572", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 33, Sharyland Plantation Village El Sendero Subdivision Phase II, Mission, Hidalgo County, Texas, Vol 43 Pg 144", subdivision: "Sharyland Plantation Village El Sendero Subdivision Phase II", lot: "33", block: null, saleDateISO: "2026-10-06", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2005-04-29", instrumentNumber: "1467042", grantorNames: "Priscilla Michelle Garcia, Marco Antonio Aparicio, Hilaria Garcia, and George L Garcia", entityType: "INDIVIDUAL", origMortgagee: "MERS", currentMortgagee: "Wells Fargo Bank, N.A.", servicerName: null, principalCents: 17_337_200, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118193", pdfFilename: "18118310_302546486_docimage_actual.pdf", address: "508 Ramirez Ln", city: "Mission", zip: "78573", addressMethod: "EXPLICIT_STATED", legalRawText: null, subdivision: null, lot: null, block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2020-05-15", instrumentNumber: "3113262", grantorNames: "Tomasito Garza, joined pro forma by spouse Norma Uvalle Rocha", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for Wallick and Volk, Inc.", currentMortgagee: "Idaho Housing and Finance Association", servicerName: null, principalCents: 21_205_000, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118194", pdfFilename: "18118310_302694331_docimage_actual.pdf", address: null, city: "Weslaco", zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 1, Crosswinds Subdivision, Weslaco, Hidalgo County, Texas, Vol 34 Pg 71", subdivision: "Crosswinds Subdivision", lot: "1", block: null, saleDateISO: "2026-09-01", saleTime: "12:59 PM - 3:59 PM", saleLocation: ADMIN_BLDG, dotDateISO: "2023-06-08", instrumentNumber: "3455438", grantorNames: "Dean Chan, married person (property not homestead)", entityType: "INDIVIDUAL", origMortgagee: null, currentMortgagee: "Adelante Funding I, Ltd., a Texas limited partnership", servicerName: null, principalCents: 15_500_000, classification: "UNKNOWN", dataQualityNote: null, manualReview: false },
  { docNumber: "118195", pdfFilename: "18118310_303530946_docimage_actual.pdf", address: "2006 Roman Street", city: "Mission", zip: "78573", addressMethod: "EXPLICIT_STATED", legalRawText: "LOTS 61 and 62, Villa De Roma Phase II, Mission, Hidalgo County, Texas, Vol 37 Pg 124A", subdivision: "Villa De Roma Phase II", lot: "61 and 62", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2016-05-27", instrumentNumber: "2717155", grantorNames: "Rene Pena Jr and Deidaly Garcia, husband and wife", entityType: "INDIVIDUAL", origMortgagee: "MERS", currentMortgagee: "PennyMac Loan Services, LLC", servicerName: null, principalCents: 0, classification: "RESIDENTIAL", dataQualityNote: "Notice states the original principal amount as $0.00 -- likely a data-entry artifact in the source document. Recorded as stated, not corrected or estimated.", manualReview: true },
  { docNumber: "118196", pdfFilename: "18118310_303530954_docimage_actual.pdf", address: "3103 Huisache Ave", city: "Hidalgo", zip: "78557", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 120, Valle Alto North Unit III, Hidalgo, Hidalgo County, Texas, Vol 32 Pg 113", subdivision: "Valle Alto North Unit III", lot: "120", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "1999-01-22", instrumentNumber: "1999-748921", grantorNames: "Jose U. Urena and wife San Juana Urena", entityType: "INDIVIDUAL", origMortgagee: "United States of America, acting through Rural Housing Service / USDA", currentMortgagee: "United States of America, acting through Rural Housing Service, USDA", servicerName: null, principalCents: null, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118198", pdfFilename: "18118310_303539016_docimage_actual.pdf", address: "705 N Inspiration Blvd", city: "Alton", zip: "78573", addressMethod: "EXPLICIT_STATED", legalRawText: "North 5 acres of the North 9.59 acres of LOT 44 (subdivision name obscured by handwriting on the source document), Hidalgo County, Texas; 4.99 acres, more or less; Parcel ID G59003A000004420", subdivision: null, lot: "44 (N 5ac of N 9.59ac)", block: null, saleDateISO: "2026-10-06", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2018-03-16", instrumentNumber: "2899122", grantorNames: "Grantor name obscured by handwritten annotation on the source notice (not recoverable)", entityType: "INDIVIDUAL", origMortgagee: null, currentMortgagee: "Freedom Mortgage Corporation", servicerName: null, principalCents: null, classification: "RESIDENTIAL", dataQualityNote: "Grantor name, principal amount, and subdivision name are obscured by handwritten annotations on the source document. Property address and metes-and-bounds legal description were legible and are recorded as stated.", manualReview: true },
  { docNumber: "118202", pdfFilename: "18118310_303539018_docimage_actual.pdf", address: null, city: "Weslaco", zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 1, Springwood Estates, Weslaco, Hidalgo County, Texas, Vol 50 Pg 154", subdivision: "Springwood Estates", lot: "1", block: null, saleDateISO: "2026-10-06", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2020-09-17", instrumentNumber: "3149847", grantorNames: "Cristian Jessel Santoyo and Itzel Neaves-Santoyo, husband and wife", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for Caliber Home Loans, Inc.", currentMortgagee: "NewRez LLC", servicerName: "Shellpoint Mortgage Servicing", principalCents: 17_477_500, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118201", pdfFilename: "18118310_303539019_docimage_actual.pdf", address: null, city: null, zip: null, addressMethod: "UNRESOLVED", legalRawText: "East 5.0 acres of LOT 12, BLOCK 53, Alamo Land and Sugar Company's Subdivision, Hidalgo County, Texas, Vol 1 Pg 24", subdivision: "Alamo Land and Sugar Company's Subdivision", lot: "12 (East 5.0 acres)", block: "53", saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2021-12-03", instrumentNumber: "3288856", grantorNames: "Crystal Starr Ybarra Sierra and Elias Daniel Sierra, wife and husband", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for Willow Bend Mortgage Company LLC", currentMortgagee: "Onslow Bay Financial LLC", servicerName: "Onity Mortgage Corporation", principalCents: 27_160_000, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118206", pdfFilename: "18118310_303547549_docimage_actual.pdf", address: null, city: null, zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 34, Casa De Los Vecinos Subdivision, Hidalgo County, Texas, Vol 21 Pg 177", subdivision: "Casa De Los Vecinos Subdivision", lot: "34", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM - 1:00 PM", saleLocation: ADMIN_BLDG, dotDateISO: "2009-11-17", instrumentNumber: "2009-2053428", grantorNames: "Jesus P. Gonzalez and Gloria Gonzalez", entityType: "INDIVIDUAL", origMortgagee: "Citifinancial, Inc.", currentMortgagee: "Magerick, LLC", servicerName: "Land Home Financial Services, Inc.", principalCents: 2_319_006, classification: "RESIDENTIAL", dataQualityNote: "Texas Home Equity (First Lien) instrument, modified by an Extension Request and Agreement dated May 31, 2013.", manualReview: false },
  { docNumber: "118204", pdfFilename: "18118310_303547554_docimage_actual.pdf", address: null, city: "Alton", zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 35, Dos Valles Subdivision Phase 2, Alton, Hidalgo County, Texas, Vol 46 Pg 170", subdivision: "Dos Valles Subdivision Phase 2", lot: "35", block: null, saleDateISO: "2026-10-06", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "2022-10-31", instrumentNumber: "3394534", grantorNames: "David Garza and Ana Victoria Garza, husband and wife", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for Willow Bend Mortgage Company LLC", currentMortgagee: "Planet Home Lending, LLC", servicerName: null, principalCents: null, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118205", pdfFilename: "18118310_303547559_docimage_actual.pdf", address: "2218 South Tourist Drive", city: "Edinburg", zip: "78539", addressMethod: "COMMONLY_KNOWN_AS_PHRASE", legalRawText: "APN 702051 / E6120-00-000-0001-00 (legal description per attached Exhibit A, not separately transcribed)", subdivision: null, lot: null, block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM - 1:00 PM", saleLocation: ADMIN_BLDG, dotDateISO: "2024-11-19", instrumentNumber: "3600595", grantorNames: "VSG LLC, a Washington limited liability company", entityType: "ENTITY", origMortgagee: "Axelrad Capital LLC, a Texas LLC", currentMortgagee: "U.S. Bank Trust Company, National Association, as Trustee for Velocity Commercial Capital Loan Trust 2025-1", servicerName: "PHH Mortgage Services / Onity Mortgage", principalCents: null, classification: "COMMERCIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118207", pdfFilename: "18118310_303957194_docimage_actual.pdf", address: "503 W Garrison Dr", city: "Pharr", zip: "78577", addressMethod: "COMMONLY_KNOWN_AS_PHRASE", legalRawText: "LOT 66, Brentwood Estates, Pharr, Hidalgo County, Texas, Doc 3024043", subdivision: "Brentwood Estates", lot: "66", block: null, saleDateISO: "2026-10-06", saleTime: "10:00 AM", saleLocation: COURTHOUSE, dotDateISO: "2023-01-06", instrumentNumber: "3411050", grantorNames: "Mario A Palacios Jr and Kayla M Palacios, a married couple", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for Synergy One Lending, Inc.", currentMortgagee: "Freedom Mortgage Corporation", servicerName: null, principalCents: null, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118208", pdfFilename: "18118310_306756758_docimage_actual.pdf", address: "5304 North 38th Lane", city: "McAllen", zip: "78504", addressMethod: "EXPLICIT_STATED", legalRawText: "LOT 9, Brookwood Subdivision Unit III, McAllen, Hidalgo County, Texas, Vol 34 Pg 67", subdivision: "Brookwood Subdivision Unit III", lot: "9", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM", saleLocation: ADMIN_BLDG, dotDateISO: "1999-11-22", instrumentNumber: "825635", grantorNames: "Belkis Aristy", entityType: "INDIVIDUAL", origMortgagee: "Obra Homes, Inc.", currentMortgagee: "U.S. Bank Trust National Association, as Owner Trustee for RCF 2 Acquisition Trust", servicerName: "Selene Finance LP", principalCents: 5_490_000, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118212", pdfFilename: "18118310_306756760_docimage_actual.pdf", address: null, city: "Mission", zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 70, Bouganvilla Estates, Mission, Hidalgo County, Texas, Vol 45 Pg 121", subdivision: "Bouganvilla Estates", lot: "70", block: null, saleDateISO: "2026-10-06", saleTime: "10:00 AM", saleLocation: AREA_DESIGNATED, dotDateISO: "2024-07-23", instrumentNumber: "3567602", grantorNames: "Xavier Edwin Garcia, a single man", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for CMG Mortgage, Inc. dba CMG Home Loans", currentMortgagee: "Lakeview Loan Servicing, LLC", servicerName: "LoanCare, LLC", principalCents: null, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118211", pdfFilename: "18118310_306756762_docimage_actual.pdf", address: null, city: "Weslaco", zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 9, BLOCK 3, Bellaire Subdivision, Weslaco, Hidalgo County, Texas, Vol 24 Pg 67", subdivision: "Bellaire Subdivision", lot: "9", block: "3", saleDateISO: "2026-10-06", saleTime: "10:00 AM", saleLocation: AREA_DESIGNATED, dotDateISO: "2023-04-03", instrumentNumber: "3436681", grantorNames: "George Adrian Guajardo, an unmarried person, and Isabel Lozano, an unmarried person", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for Willow Bend Mortgage Company LLC", currentMortgagee: "PennyMac Loan Services, LLC", servicerName: null, principalCents: null, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118213", pdfFilename: "18118310_306766118_docimage_actual.pdf", address: "5302 N Ezequiel Loop", city: "Mission", zip: "78574", addressMethod: "COMMONLY_KNOWN_AS_PHRASE", legalRawText: "LOT 7, BLOCK 1, Acevedo Subdivision Unit No. 3, Hidalgo County, Texas, Vol 23 Pg 93-B", subdivision: "Acevedo Subdivision Unit No. 3", lot: "7", block: "1", saleDateISO: "2026-10-06", saleTime: "10:00 AM", saleLocation: COURTHOUSE, dotDateISO: "2022-04-12", instrumentNumber: "3332600", grantorNames: "Elvia P Garza, an unmarried woman", entityType: "INDIVIDUAL", origMortgagee: "MERS nominee for InterLinc Mortgage Services, LLC", currentMortgagee: "Freedom Mortgage Corporation", servicerName: null, principalCents: null, classification: "RESIDENTIAL", dataQualityNote: null, manualReview: false },
  { docNumber: "118219", pdfFilename: "18118310_308205378_docimage_actual.pdf", address: null, city: null, zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 34, Elite Village Subdivision Phase II, Hidalgo County, Texas, Clerk's File 2239313", subdivision: "Elite Village Subdivision Phase II", lot: "34", block: null, saleDateISO: "2026-09-01", saleTime: "1:00 PM - 4:00 PM", saleLocation: "Hidalgo County, Texas", dotDateISO: "2014-04-03", instrumentNumber: "2506256", grantorNames: "Mario A. Rodriguez and Sofia A. Gonzalez de Rodriguez", entityType: "INDIVIDUAL", origMortgagee: null, currentMortgagee: "Top Fruit, Inc., a Texas corporation", servicerName: null, principalCents: 3_440_000, classification: "UNKNOWN", dataQualityNote: null, manualReview: false },
  { docNumber: "118223", pdfFilename: "18118310_308205380_docimage_actual.pdf", address: null, city: null, zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 32, Cardinal Island Subdivision, Hidalgo County, Texas, Clerk's File 2575027", subdivision: "Cardinal Island Subdivision", lot: "32", block: null, saleDateISO: "2026-09-01", saleTime: "1:00 PM - 4:00 PM", saleLocation: "Hidalgo County, Texas", dotDateISO: "2017-12-11", instrumentNumber: "2875772", grantorNames: "Miriam Zuniga-Polanco and Daniel Rivera-Garza", entityType: "INDIVIDUAL", origMortgagee: "Cardinal Lots, Ltd., a Texas limited partnership", currentMortgagee: "Franz Reinhold Schamberger a/k/a Reinhold Schamberger", servicerName: null, principalCents: 3_470_000, classification: "UNKNOWN", dataQualityNote: "Note transferred from original mortgagee Cardinal Lots, Ltd. to Franz Reinhold Schamberger a/k/a Reinhold Schamberger by a Transfer of Lien dated November 30, 2025.", manualReview: false },
  { docNumber: "118227", pdfFilename: "18118310_308946700_docimage_actual.pdf", address: null, city: null, zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 54, San Jacinto Estates No. 4 Phase II, Hidalgo County, Texas, Clerk's File 3369505", subdivision: "San Jacinto Estates No. 4 Phase II", lot: "54", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM CST", saleLocation: ADMIN_BLDG, dotDateISO: "2023-04-29", instrumentNumber: "3475494", grantorNames: "Abiel Sergio Martinez Jr and Ana Rosa Lopez", entityType: "INDIVIDUAL", origMortgagee: null, currentMortgagee: "San Jacinto Enterprises, LLC, a Texas LLC", servicerName: null, principalCents: 6_850_000, classification: "UNKNOWN", dataQualityNote: null, manualReview: false },
  { docNumber: "118226", pdfFilename: "18118310_308946703_docimage_actual.pdf", address: null, city: null, zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 141, San Jacinto Estates No. 10 Phase I, Hidalgo County, Texas, Instrument No. 3276440", subdivision: "San Jacinto Estates No. 10 Phase I", lot: "141", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM CST", saleLocation: ADMIN_BLDG, dotDateISO: "2024-06-08", instrumentNumber: "3567336", grantorNames: "Jesus Rodriguez and wife Maria Isabel Soliz", entityType: "INDIVIDUAL", origMortgagee: null, currentMortgagee: "Charles A. Crockett and wife Carolina G. Crockett", servicerName: null, principalCents: 32_800_000, classification: "UNKNOWN", dataQualityNote: null, manualReview: false },
  { docNumber: "118224", pdfFilename: "18118310_308946705_docimage_actual.pdf", address: null, city: null, zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 139, San Jacinto Estates No. 10 Phase I, Hidalgo County, Texas, Instrument No. 3276440", subdivision: "San Jacinto Estates No. 10 Phase I", lot: "139", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM CST", saleLocation: ADMIN_BLDG, dotDateISO: "2024-04-19", instrumentNumber: "3550325", grantorNames: "Senaida Ann Salinas", entityType: "INDIVIDUAL", origMortgagee: "Jacinto Garza, II", currentMortgagee: "San Jacinto Enterprises, LLC, a Texas LLC", servicerName: null, principalCents: 33_000_000, classification: "UNKNOWN", dataQualityNote: null, manualReview: false },
  { docNumber: "118230", pdfFilename: "18118310_308946706_docimage_actual.pdf", address: null, city: null, zip: null, addressMethod: "UNRESOLVED", legalRawText: "LOT 21, San Jacinto Estates No 10 Phase I Subdivision, Hidalgo County, Texas, Clerk's File 3276440", subdivision: "San Jacinto Estates No. 10 Phase I", lot: "21", block: null, saleDateISO: "2026-09-01", saleTime: "10:00 AM CST", saleLocation: ADMIN_BLDG, dotDateISO: "2021-12-09", instrumentNumber: "3290008", grantorNames: "Evelin Hernandez Pinales", entityType: "INDIVIDUAL", origMortgagee: null, currentMortgagee: "San Jacinto Enterprises, LLC, a Texas LLC", servicerName: null, principalCents: 3_850_000, classification: "UNKNOWN", dataQualityNote: "Same borrower, Deed of Trust date, and principal amount as a separate notice covering adjacent Lot 22 (different instrument number, 3290024); recorded as a distinct case because it is a distinct recording instrument and lot.", manualReview: false },
];
